*EXECUTE_UNLOAD 'SCUCRESULTS',GEN_BLOCK_SCHEDULE,GEN_SCHEDULE,GEN_RESERVE_SCHEDULE,UNIT_STATUS,UNIT_STARTUP,UNIT_SHUTDOWN,GEN_OPCOST_BY_INTERVAL,NOLOADCOST_BY_INTERVAL,STARTUPCOST_BY_INTERVAL,LINEFLOW,PNLS,THETA;
EXECUTE '=GDX2ACCESS SCUC_p1.GDX'
